### PR TITLE
Fix some typos and Markdown formatting in Part 1

### PR DESCRIPTION
**Pull request by adrian5**

### CODE REVIEW

**Comment by cfsamson** [comment]
Sorry for taking so long to getting around to review these. I really appreciate getting these kind fixes so if you spot more I'll be happy to merge them.

**Comment by adrian5** [comment]
No problem! Thanks a lot for these great books btw, they've been immensely helpful as an introduction to async I/O. I struggled with the official Rust async book, and your style of explaining allowed me to make more headway.

**Comment by cfsamson** [comment]
That's great to hear. You can also check out the book on [Futures and async/await](https://cfsamson.github.io/books-futures-explained/) if you're not aware of it yet. It's a pretty deep dive, but for me, it helps a lot to remove some of the abstraction layers to understand what's going on.

**Comment by adrian5** [comment]
That's next on my list! I landed there first but then decided to start with your other two books (which were mentioned), as a prelude.

**Pull request merged**
